// ignore_for_file: unnecessary_string_interpolations

import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:pdf/pdf.dart';
import 'dart:typed_data';

import '../models/report_model.dart';


class PdfService {


static Future<void> generateReport(

ReportModel report,

Uint8List? temperatureImage,

Uint8List? gasImage,

) async {


final pdf = pw.Document();


String gasStatus;
PdfColor statusColor;


if(report.gas > 700){

gasStatus = "DANGER - HIGH GAS LEVEL";
statusColor = PdfColors.red;

}

else{

gasStatus = "SAFE";
statusColor = PdfColors.green;

}



pdf.addPage(

pw.MultiPage(

pageFormat: PdfPageFormat.a4,

margin:
const pw.EdgeInsets.all(30),


header:(context)=>


pw.Container(

padding:
const pw.EdgeInsets.all(15),

decoration:
pw.BoxDecoration(

color:
PdfColors.blue900,

borderRadius:
pw.BorderRadius.circular(10),

),


child:

pw.Row(

mainAxisAlignment:
pw.MainAxisAlignment.spaceBetween,

children:[


pw.Text(

"SMART SAFETY VEST",

style:
pw.TextStyle(

color:
PdfColors.white,

fontSize:22,

fontWeight:
pw.FontWeight.bold,

)

),



pw.Text(

"Safety Report",

style:
pw.TextStyle(

color:
PdfColors.white,

fontSize:14,

)

),



]

)

),




footer:(context)=>

pw.Center(

child:

pw.Text(

"Generated by Smart Safety Vest Monitoring System",

style:

const pw.TextStyle(

fontSize:10,

color:
PdfColors.grey,

)

)

),




build:(context)=>[



pw.SizedBox(height:20),



// REPORT INFORMATION


pw.Container(

padding:
const pw.EdgeInsets.all(15),

decoration:
pw.BoxDecoration(

border:
pw.Border.all(

color:
PdfColors.grey300

),

borderRadius:
pw.BorderRadius.circular(10)

),


child:

pw.Column(

crossAxisAlignment:
pw.CrossAxisAlignment.start,


children:[


pw.Text(

"Worker Information",

style:
pw.TextStyle(

fontSize:18,

fontWeight:
pw.FontWeight.bold

)

),


pw.SizedBox(height:10),



pw.Text(
"Worker ID : ${report.workerId}"
),


pw.Text(
"Report Type : Safety Monitoring Report"
),


pw.Text(
"Generated Time : ${DateTime.now()}"
),


]

)

),




pw.SizedBox(height:20),





// STATUS CARD


pw.Container(

padding:
const pw.EdgeInsets.all(15),

decoration:
pw.BoxDecoration(

color:
statusColor,

borderRadius:
pw.BorderRadius.circular(10)

),


child:

pw.Center(

child:

pw.Text(

gasStatus,

style:
pw.TextStyle(

color:
PdfColors.white,

fontSize:18,

fontWeight:
pw.FontWeight.bold

)

)

)

),





pw.SizedBox(height:25),





// ENVIRONMENT SECTION


pw.Text(

"ENVIRONMENT MONITORING",

style:
pw.TextStyle(

fontSize:20,

fontWeight:
pw.FontWeight.bold

)

),


pw.Divider(),



pw.Table(

border:
pw.TableBorder.all(

color:
PdfColors.grey300

),


children:[



_createRow(
"Temperature Average",
"${report.temperatureAvg.toStringAsFixed(2)} °C"
),


_createRow(
"Maximum Temperature",
"${report.temperatureMax.toStringAsFixed(2)} °C"
),


_createRow(
"Minimum Temperature",
"${report.temperatureMin.toStringAsFixed(2)} °C"
),


_createRow(
"Humidity",
"${report.humidity.toStringAsFixed(2)}%"
),


_createRow(
"Gas Level",
"${report.gas.toStringAsFixed(0)} ppm"
),



]


),





pw.SizedBox(height:20),





if(temperatureImage != null)

pw.Column(

crossAxisAlignment:
pw.CrossAxisAlignment.start,

children:[


pw.Text(

"Temperature Graph",

style:
pw.TextStyle(

fontSize:16,

fontWeight:
pw.FontWeight.bold

)

),


pw.SizedBox(height:10),


pw.Center(

child:

pw.Image(

pw.MemoryImage(
temperatureImage
),

height:180

)

),


]

),




pw.SizedBox(height:20),




if(gasImage != null)

pw.Column(

crossAxisAlignment:
pw.CrossAxisAlignment.start,

children:[


pw.Text(

"Gas Monitoring Graph",

style:
pw.TextStyle(

fontSize:16,

fontWeight:
pw.FontWeight.bold

)

),



pw.SizedBox(height:10),


pw.Center(

child:

pw.Image(

pw.MemoryImage(
gasImage
),

height:180

)

),


]

),





pw.SizedBox(height:25),






// HEALTH


pw.Text(

"HEALTH STATUS",

style:
pw.TextStyle(

fontSize:20,

fontWeight:
pw.FontWeight.bold

)

),


pw.Divider(),



_createInfoCard(

"Heart Rate",

"${report.heartRate.toStringAsFixed(0)} BPM"

),






pw.SizedBox(height:20),





// LOCATION


pw.Text(

"LOCATION DETAILS",

style:
pw.TextStyle(

fontSize:20,

fontWeight:
pw.FontWeight.bold

)

),


pw.Divider(),



_createInfoCard(

"Latitude",

"${report.latitude.toStringAsFixed(6)}"

),



_createInfoCard(

"Longitude",

"${report.longitude.toStringAsFixed(6)}"
),



pw.SizedBox(height:10),



pw.Text(

"Google Maps Location",

style:
pw.TextStyle(

fontWeight:
pw.FontWeight.bold

)

),


pw.Text(

"https://maps.google.com/?q=${report.latitude},${report.longitude}",

style:
const pw.TextStyle(

fontSize:10

)

),



]

)

);



await Printing.layoutPdf(

onLayout:(format)=>pdf.save()

);



}




static pw.TableRow _createRow(

String title,

String value

){


return pw.TableRow(

children:[


pw.Padding(

padding:
const pw.EdgeInsets.all(8),

child:

pw.Text(

title,

style:
pw.TextStyle(

fontWeight:
pw.FontWeight.bold

)

)

),



pw.Padding(

padding:
const pw.EdgeInsets.all(8),

child:

pw.Text(value)

),


]

);


}





static pw.Widget _createInfoCard(

String title,

String value

){


return pw.Container(

margin:
const pw.EdgeInsets.only(bottom:8),


padding:
const pw.EdgeInsets.all(12),


decoration:

pw.BoxDecoration(

border:
pw.Border.all(

color:
PdfColors.grey300

),

borderRadius:
pw.BorderRadius.circular(8)

),



child:

pw.Row(

mainAxisAlignment:
pw.MainAxisAlignment.spaceBetween,


children:[


pw.Text(

title,

style:
pw.TextStyle(

fontWeight:
pw.FontWeight.bold

)

),


pw.Text(value)


]


)


);


}


}