// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDWakiO8V17fPGEnLRueCt91SqK6app3M',
    appId: '1:124855601708:web:e6ed12f66e95d5d4a0df89',
    messagingSenderId: '124855601708',
    projectId: 'cw-project-4212c',
    authDomain: 'cw-project-4212c.firebaseapp.com',
    databaseURL: 'https://cw-project-4212c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cw-project-4212c.firebasestorage.app',
    measurementId: 'G-V3RY1CFJ2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKIXgRP1zfm5qzGR1oS4X36gwp9P0URlA',
    appId: '1:124855601708:android:8d3a55f5e6abe3e6a0df89',
    messagingSenderId: '124855601708',
    projectId: 'cw-project-4212c',
    databaseURL: 'https://cw-project-4212c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cw-project-4212c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7wSlvJVkQ8kApYwJU5H4RAgWeHaDy27w',
    appId: '1:124855601708:ios:e79589cec0d1fd17a0df89',
    messagingSenderId: '124855601708',
    projectId: 'cw-project-4212c',
    databaseURL: 'https://cw-project-4212c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cw-project-4212c.firebasestorage.app',
    iosBundleId: 'com.example.safetyVestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7wSlvJVkQ8kApYwJU5H4RAgWeHaDy27w',
    appId: '1:124855601708:ios:e79589cec0d1fd17a0df89',
    messagingSenderId: '124855601708',
    projectId: 'cw-project-4212c',
    databaseURL: 'https://cw-project-4212c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cw-project-4212c.firebasestorage.app',
    iosBundleId: 'com.example.safetyVestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDWakiO8V17fPGEnLRueCt91SqK6app3M',
    appId: '1:124855601708:web:33e31dcb806b8182a0df89',
    messagingSenderId: '124855601708',
    projectId: 'cw-project-4212c',
    authDomain: 'cw-project-4212c.firebaseapp.com',
    databaseURL: 'https://cw-project-4212c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cw-project-4212c.firebasestorage.app',
    measurementId: 'G-1JJ9JKZKE1',
  );
}
